version: '3.8'
services:
  # nest-admin-web:
  #   image: buqiyuan/vue3-antdv-admin:stable
  #   container_name: nest-admin-web
  #   volumes:
  #     - ./deploy/web:/etc/nginx/conf.d
  #   ports:
  #     - '10010:80'
  #   restart: always
  #   networks:
  #     - nest_admin_net

  mysql:
    image: mysql:latest
    container_name: fast-api-ai
    restart: always
    # env_file:
    #   - .env
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=23306
      - MYSQL_DATABASE=FastAPI
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Qwer1234
      - MYSQL_ROOT_PASSWORD=Qwer1234

    ports:
      - '23306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集
    # volumes:
      # - ./__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
      # - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本


  # nest-admin-server:
    # build: 从当前路径构建镜像
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - PROJECT_DIR=${PROJECT_DIR}
    # image: buqiyuan/nest-admin-server:stable
    # container_name: nest-admin-server
    # restart: always
    # env_file:
    #   - .env
    #   - .env.production
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    # ports:
    #   - '${APP_PORT}:${APP_PORT}'
    # volumes:
    #   - ./logs/:${PROJECT_DIR}/logs/ # ./logs 日志文件挂载到容器外部
    # # 当前服务启动之前先要把depends_on指定的服务启动起来才行
    # depends_on:
    #   - mysql
    #   - redis
    # networks:
    #   - nest_admin_net    

# volumes:
#   nest-mysql:
#     name: nest-mysql-db


# networks:
#   nest_admin_net:
#     name: nest_admin_net
#     # driver: custom-driver-1


